routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { //Se puede colocar cualquier ruta deseada
  //  return view('welcome'); //Vista ubicada en Recursos >> Vistas
//});

//Route::get('/empleados', 'EmpleadosController@index');


Route::get('/', function () {
  return view('welcome');
});

Route::resource('empleados', 'EmpleadosController')->middleware('auth'); //Validar sesión en la ruta.
Route::resource('bibliotecario', 'BibliotecarioController')->middleware('auth');
Route::resource('libros', 'LibrosController')->middleware('auth');
Route::resource('libros2', 'Libros2Controller')->middleware('auth');
Route::resource('clientes', 'ClientesController')->middleware('auth'); //Validar sesión en la ruta.
Route::resource('clientes2', 'Clientes2Controller')->middleware('auth'); //Validar sesión en la ruta.

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//modelo bibliotecarios utilizando la tabla empleados.

//Route::get('/Bibliotecario/login', function () {
//  return view('Bibliotecario.login'); //Ruta para cargar el login bibliotecario
//});
Route::get('Bibliotecario/login', 'BibliotecarioController@showLoginForm');

//Route::get('/Bibliotecario/inicio', 'BibliotecarioController@index')->name('inicio');
Route::post('Bibliotecario/inicio', 'BibliotecarioController@login')->name('inicio'); //Ruta de inicio para bibliotecario
//Route::get('Bibliotecario/inicio', 'BibliotecarioController@secret');

Route::get('Bibliotecario/inicio', function () {
  return view('Bibliotecario.inicio');
}) ->name('inicio');

//Route::group(['middleware' => ['auth']], function () {
 // Route::resource('bibliotecario', 'BibliotecarioController');
//}); //Ruta para proteger el directorio bibliotecario, solo con usuario logueado

app/Bibliotecario.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Bibliotecario extends Authenticatable
{
    //
    

       /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'empleados';
    protected $fillable = [
        'Nombre', 'Correo', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BibliotecarioController.php
<?php

namespace App\Http\Controllers;

//use App\Http\Requests;
//use Illuminate\Http\Request;


use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class BibliotecarioController extends Controller
{
    use AuthenticatesUsers;



   public function showLoginForm(){

        return view('bibliotecario.login'); 

    }

    protected $guard ='empleados';

    public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if (method_exists($this, 'hasTooManyLoginAttempts') &&
            $this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }

    /**
     * Validate the user login request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function validateLogin(Request $request)
    {
        $request->validate([
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    /**
     * Attempt to log the user into the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function attemptLogin(Request $request)
    {
        return $this->guard()->attempt(
            $this->credentials($request), $request->filled('remember')
        );
    }

    /**
     * Get the needed authorization credentials from the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    
      protected function credentials(Request $request)
    {
        return $request->only($this->username(), 'password');
    } 

    /**
     * Send the response after the user was authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
                ?: redirect()->intended($this->redirectPath());
    }

    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated()
    {
        //
        return redirect('Bibliotecario/inicio');
    }

    protected function secret()
    {
        //
        return 'Hola';
    }

    /**
     * Get the failed login response instance.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function sendFailedLoginResponse(Request $request)
    {
        throw ValidationException::withMessages([
            $this->username() => [trans('auth.failed')],
        ]);
    }

    /**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        return $this->loggedOut($request) ?: redirect('/');
    }

    /**
     * The user has logged out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    protected function loggedOut(Request $request)
    {
        //
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }

    

    //public function index()
    //{
      //      return 'sesión iniciada';   
   // }
}

resources/views/bibliotecario/inicio.blade.php
<title>BiblioMundo</title>
        <link rel="shortcut icon" href="../../public/books.ico" />
@extends('layouts.app3')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Administración</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

     <input type="button" onclick="location.href = '{{ route('clientes2.index') }}'"
     class="btn btn-primary" value="Gestión de Clientes">
<input type="button" onclick="location.href = '{{ route('libros2.index') }}'"
     class="btn btn-primary" value="Gestión de Libros">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('DASHBOARD DE BIBLIOTECARIOS') }}</div>

                
            </div>
        </div>
    </div>
</div> -->
@endsection

resources/views/bibliotecario/login.blade.php
<title>BiblioMundo</title>
        <link rel="shortcut icon" href="../../public/books.ico" />
@extends('layouts.app2')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Inicio de Sesión Bibliotecario') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ url('/Bibliotecario/inicio') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Dirección E-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Contraseña') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                   <!-- <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>--> 
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection